CREATE DATABASE IF NOT EXISTS recipe_app;
USE recipe_app;

CREATE TABLE IF NOT EXISTS user (
username VARCHAR(100) PRIMARY KEY,
password VARCHAR(255) NOT NULL,
role VARCHAR(50) DEFAULT 'user'
);


CREATE TABLE IF NOT EXISTS recipe (
id INT AUTO_INCREMENT PRIMARY KEY,
created_by VARCHAR(100) NOT NULL,
title VARCHAR(255) NOT NULL,
cooking_time INT NOT NULL,
instructions TEXT NOT NULL,
ingredients TEXT NOT NULL,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
FOREIGN KEY (created_by) REFERENCES user(username)
);


CREATE TABLE IF NOT EXISTS review (
id INT AUTO_INCREMENT PRIMARY KEY,
recipe_id INT NOT NULL,
created_by VARCHAR(100) NOT NULL,
comment TEXT,
rating INT NOT NULL CHECK (rating BETWEEN 1 AND 5),
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
FOREIGN KEY (recipe_id) REFERENCES recipe(id) ON DELETE CASCADE,
FOREIGN KEY (created_by) REFERENCES user(username) ON DELETE CASCADE
);


CREATE TABLE IF NOT EXISTS favorite (
created_by VARCHAR(255) NOT NULL,
recipe_id INT NOT NULL,
PRIMARY KEY (created_by, recipe_id),
FOREIGN KEY (created_by) REFERENCES user(username) ON DELETE CASCADE,
FOREIGN KEY (recipe_id) REFERENCES recipe(id) ON DELETE CASCADE
);